version: 2
updates:
  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /apps
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /apps/homadctl
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /apps/speed-dial
    schedule:
     interval: daily
