version: 2
updates:
  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /apps
    schedule:
      interval: daily
