snapshot:
  name_template: "{{ .Commit }}"

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: "homadctl"
    hooks:
      post:
        - cmd: upx {{ .Path }}

dockers:
  - id: linux_amd64
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/davidsbond/homad-homadctl:{{ .Commit }}-amd64"
      - "ghcr.io/davidsbond/homad-homadctl:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"

  - id: linux_arm64
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/davidsbond/homad-homadctl:{{ .Commit }}-arm64"
      - "ghcr.io/davidsbond/homad-homadctl:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/davidsbond/homad-homadctl:latest"
    image_templates:
      - "ghcr.io/davidsbond/homad-homadctl:latest-amd64"
      - "ghcr.io/davidsbond/homad-homadctl:latest-arm64"
  - name_template: "ghcr.io/davidsbond/homad-homadctl:{{ .Commit }}"
    image_templates:
      - "ghcr.io/davidsbond/homad-homadctl:{{ .Commit }}-amd64"
      - "ghcr.io/davidsbond/homad-homadctl:{{ .Commit }}-arm64"

release:
  disable: true

checksum:
  disable: true

changelog:
  skip: true
