name: speed-dial
on:
  push:
    tags:
      - "*"
    branches:
      - master
    paths:
      - 'apps/speed-dial/**'
      - 'apps/go.mod'
      - 'apps/go.sum'
      - '.github/workflows/speed-dial.yml'
  pull_request:
    paths:
      - 'apps/speed-dial/**'
      - 'apps/go.mod'
      - 'apps/go.sum'
      - '.github/workflows/speed-dial.yml'

jobs:
  vet:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: apps/go.mod
          cache-dependency-path: apps/go.sum

      - name: Vet
        working-directory: apps/speed-dial
        run: go vet ./...

  release:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - vet
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: apps/go.mod
          cache-dependency-path: apps/go.sum

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
          workdir: apps/speed-dial
        env:
          GITHUB_TOKEN: ${{ github.token }}
