name: terraform
on:
  push:
    branches:
      - master
    paths:
      - '**.tf'
      - '**.nomad'
      - '.github/workflows/terraform.yml'
  pull_request:
    paths:
      - '**.tf'
      - '**.nomad'
      - '.github/workflows/terraform.yml'

jobs:
  format:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        run: make format

  plan:
    concurrency: terraform
    needs:
      - format
    runs-on: ubuntu-20.04
    if: (github.actor != 'dependabot[bot]') && !startsWith(github.head_ref, 'dependabot/')
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: terraform/.terraform
          key: ${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Unlock git-crypt
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Connect to Tailnet
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: make init

      - name: Terraform Plan
        id: plan
        run: make plan

      - name: Add plan output to PR
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            <details>
              <summary>
                Output of plan:
              </summary>
              <pre>${{steps.plan.outputs.stdout}}</pre>
            </details>
          GITHUB_TOKEN: ${{ github.token }}

  apply:
    concurrency: terraform
    needs:
      - plan
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: terraform/.terraform
          key: ${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Unlock git-crypt
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Connect to Tailnet
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: make init

      - name: Terraform Plan
        run: make plan

      - name: Terraform Apply
        run: make apply
